# Generated by Django 5.0.1 on 2025-07-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator_api', '0003_rename_fingerprint_scan_id_port_idx_fingerprint_scan_id_970192_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fingerprintdetail',
            new_name='fingerprint_scan_id_970192_idx',
            old_name='fingerprint_scan_id_port_idx',
        ),
        migrations.RenameIndex(
            model_name='fingerprintdetail',
            new_name='fingerprint_target__e61581_idx',
            old_name='fingerprint_target_id_port_idx',
        ),
    ]
